/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: 'class',
	theme: {
		extend: {
			colors: {
				"accent": "#a3160b",
        "primary": "#171717",
				"secondary": "#d4d4d4",
			},
			fontFamily: {
				sans: [
          'freight-big-pro',
					'Poppins',
					'Roboto',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Roboto',
					'"Helvetica Neue"',
					'Arial',
					'"Noto Sans"',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
        display: [
          'TimmonsNY',
          'freight-big-pro',
        ],
        micro: [
          'freight-big-pro',
          'system-ui',
          'Inter',
          'Roboto',
        ],
				serif: [
          'freight-big-pro',
          'Merriweather',
          'ui-serif',
          'Georgia',
          'Cambria',
          '"Times New Roman"',
          'Times',
          'serif',
        ],
				mono: [
					'ui-monospace',
					'SFMono-Regular',
					'Menlo',
					'Monaco',
					'Consolas',
					'"Liberation Mono"',
					'"Courier New"',
					'monospace',
				],
			},
      fontSize: {
        'clamp-xs': [`clamp(0.75rem, 1vw, 0.875rem)`, { lineHeight: '1rem' }],
        'clamp-sm': [`clamp(0.875rem, 1.125vw, 1rem)`, { lineHeight: '1.25rem' }],
        'clamp-base': [`clamp(1rem, 1.25vw, 1.125rem)`, { lineHeight: '1.5rem' }],
        'clamp-lg': [`clamp(1.125rem, 1.5vw, 1.25rem)`, { lineHeight: '1.75rem' }],
        'clamp-xl': [`clamp(1.25rem, 1.875vw, 1.5rem)`, { lineHeight: '1.75rem' }],
        'clamp-2xl': [`clamp(1.5rem, 2.25vw, 1.875rem)`, { lineHeight: '2rem' }],
        'clamp-3xl': [`clamp(1.875rem, 3vw, 2.25rem)`, { lineHeight: '2.25rem' }],
        'clamp-4xl': [`clamp(2.25rem, 3.75vw, 3rem)`, { lineHeight: '2.5rem' }],
        'clamp-5xl': [`clamp(2.5rem, 4.5vw, 3.75rem)`, { lineHeight: '0.75' }],
        'clamp-6xl': [`clamp(3rem, 6vw, 4.5rem)`, { lineHeight: '0.75' }],
        'clamp-7xl': [`clamp(3.75rem, 8vw, 7rem)`, { lineHeight: '0.75' }],
        'clamp-8xl': [`clamp(4rem, 12vw, 10rem)`, { lineHeight: '0.75' }],
        'clamp-9xl': [`clamp(4.5rem, 20vw, 16rem)`, { lineHeight: '0.75' }],
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      maxWidth: {
        '8xl': '92rem',
      },
			screens: {
				'xs': '500px',
				'sm': '640px',
				'md': '768px',
				'lg': '1024px',
				'xl': '1280px',
				'2xl': '1536px',
			},
      width: {
        '1/1': '100%',
      },
			zIndex: {
				'dropdown': 1000,
				'sticky': 1020,
				'fixed': 1030,
				'modal-backdrop': 1040,
				'modal': 1050,
				'popover': 1060,
				'tooltip': 1070,
        'sidebar-background': 1074,
        'sidebar': 1075,
        'cookie-banner': 1080,
        'transition-background': 1090,
        'transition-canvas': 1100,
        'transition-html': 1110,
        'cursor': 1200,
			},
		},
	},
	plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
  ],
}
