/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: 'class',
	theme: {
		extend: {
			colors: {
				"accent": "#a3160b",
        "primary": "#171717",
				"secondary": "#d4d4d4",
			},
			fontFamily: {
				sans: [
					'Inter',
          'system-ui',
					'Poppins',
					'Roboto',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Roboto',
					'"Helvetica Neue"',
					'Arial',
					'"Noto Sans"',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
        display: [
          'TimmonsNY',
          'Inter',
					'system-ui',
        ],
        micro: [
          'Inter',
					'system-ui',
          'Roboto',
        ],
				serif: [
          'Merriweather',
          'ui-serif',
          'Georgia',
          'Cambria',
          '"Times New Roman"',
          'Times',
          'serif',
        ],
				mono: [
					'ui-monospace',
					'SFMono-Regular',
					'Menlo',
					'Monaco',
					'Consolas',
					'"Liberation Mono"',
					'"Courier New"',
					'monospace',
				],
			},
      fontSize: {
        'micro': [`clamp(0.7rem, 1vh, 5rem)`, { lineHeight: '1' }],
        'body': [`clamp(1rem, 2.5vh, 6rem)`, { lineHeight: '1' }],
        'heading': [`clamp(8rem, 28vh, 80rem)`, { lineHeight: '0.8' }],
      },
      maxWidth: {
        '8xl': '92rem',
      },
			screens: {
				'xs': '500px',
				'sm': '640px',
				'md': '768px',
				'lg': '1024px',
				'xl': '1280px',
				'2xl': '1536px',
			},
      width: {
        '1/1': '100%',
      },
			zIndex: {
				'dropdown': 1000,
				'sticky': 1020,
				'fixed': 1030,
				'modal-backdrop': 1040,
				'modal': 1050,
				'popover': 1060,
				'tooltip': 1070,
        'sidebar-background': 1074,
        'sidebar': 1075,
        'cookie-banner': 1080,
        'transition-background': 1090,
        'transition-canvas': 1100,
        'transition-html': 1110,
        'cursor': 1200,
			},
		},
	},
	plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
  ],
}
